### PR TITLE
Change git flow

### PR DESCRIPTION
**Pull request by andersfylling**
In stead of using master, develop, and new branches for experimental or new features. I suggest using the master branch as the main develop branch.

With this new setup, we branch off for every release. And create new branches when working on experimental code.

This makes it easier to maintain the code when in need to do minor patches as the branched of releases will be of `v1.0` and not `v1.0.0` making the minor patch not fixed for the release.

With this users can import packages in a specific branch to get a version that stays somewhat maintained:
```
import
 - package: github.com/s1kx/unison
   version: v1.0
```

### CODE REVIEW

**Comment by andersfylling** [comment]
If this gets accepted. We should leave branch:develop alone, since bots are already using the branch and branch of master to create `v0.1` so there's a stable version to be used. Not the greatest first release, but it seems to be usable as bots work with the current code.

**Comment by s1kx** [comment]
Making `master` the development branch (read as 'unstable') makes it a little easier to jump in from a developer's perspective, however I suspect that most people pulling in dependencies don't specify a version by hand at all.

In fact, we should assume that neither Glide nor Godeps or any other dependency management tool is used, and instead just the native Go import. Then, if master is the default branch (which it is, by default eheh), we are putting out unstable code to people that expect a package that "just works".

I would say `master` should at least be second-tier to another branch, so that `master` is known to not be broken (= passing tests if we have more coverage?) - no surprises, and `develop` would be fresh meat from the farm, pending rating...

Also, version pinning as you wrote via `version: v1.0` should work via tags as well as branches, but I agree on the point of having branches for minor releases with rolling updates being beneficial. So I would suggest merging `develop` into `v0.1` and from there into `master`. What do you think?

**Comment by andersfylling** [comment]
What if master holds v1.0.0 and then some day we merge develop into master, where develop holds release v2.0.0. that will cause a break in their bot.

**Comment by s1kx** [comment]
Not if it worked initially when they pulled the dependency in, but for any person rebuilding it from their source it would... I'm just saying it wouldn't be wise to have broken code in master at any time.

I'll review the code changes in a moment and then let's see if we can go ahead to `v0.1`.

**Comment by andersfylling** [comment]
Fair enough. Can we keep the logic for branching off releases tho?

**Comment by s1kx** [comment]
Yes lets branch off for minor releases (`v$MAJOR.$MINOR`).

**Pull request merged**
